version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 10
  build:
    commands:
      - npm install
      - export BUCKET=aruni-aws-pipeline-test
      - aws cloudformation package --template-file template.yml --s3-bucket aruni-aws-pipeline-test --output-template-file outputtemplate.yaml
  post_build:
    commands:
      - newman run test/aruni-aws-pipeline-test.postman_collection.json -r json, cli --reporter-json-export report.json
artifacts:
  type: zip
  files:
    - report.json
    - template.yml
    - outputtemplate.yaml